stages:
 - source_check
 - build

variables:
 LINT_LOG: "eslint-report.txt"

eslint:
  image: registry.gitlab.gnome.org/gnome/gjs:fedora.static-analysis
  stage: source_check
  script:
    - sh lint/generate-report.sh -o $LINT_LOG || { cat $LINT_LOG; false; }
  artifacts:
    paths:
      - ${LINT_LOG}
    when: on_failure

build-shell-extensions:
  image: fedora:latest
  stage: build
  before_script:
    - dnf install -y meson gettext mozjs60-devel
  script:
    - meson _build .
    - ninja -C _build test install
