image: fedora:latest

stages:
 - build

before_script:
  - dnf install -y meson gettext mozjs60-devel

build-shell-extensions:
  stage: build
  script:
    - meson _build .
    - ninja -C _build test install
